Refactor
GodofRussia/homework-selenium-2023-autumn pull request #6
Opened 2024-01-02 13:27 UTC by stepanpopov

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/tests/base_case.py
Вроде не юзается

 @contextmanager
    def not_raises(self, exception):
        try:
            yield
        except exception as e:
            raise pytest.fail("Raised {0}".format(e))

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/tests/test_main_page.py
Мб вынести в функу Page?
 found = False
        for word in banner_words:
            if word in self.driver.page_source:
                found = True

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/tests/test_main_page_navbar.py
Driver надо убирать из тестов((
with self.switch_to_window(self.driver.current_window_handle, True):
            assert (
                self.driver.current_url
                == main_page.EXTERNAL_LINKS.SERTIFICATION_URL
            )

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/ui/pages/adv_page.py
> +)
А где юзается?

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/ui/pages/base_page.py
>          time.sleep(3)
??

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/ui/pages/base_page.py
> +        return self.driver.get_cookie(AUTH_COOKIE_NAME) != None
is not None

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/ui/pages/base_page.py
>          # self.is_opened()
Убрать коммент

2024-01-13 11:01 UTC, KolobokMysnoy commented on hw/code/ui/pages/main_page/main_page.py
return CasesPage(self.driver)
Откроет в любом случае же, зачем действия до этого?

2024-01-13 13:18 UTC, stepanpopov commented on hw/code/tests/test_main_page_navbar.py
тут переход на новую вкладку и проверка урла в пейдже, не относящемся к текущему сайту

2024-01-13 13:18 UTC, stepanpopov commented on hw/code/tests/base_case.py
убрал

2024-01-13 13:19 UTC, stepanpopov commented on hw/code/tests/test_main_page.py
вынес

2024-01-13 13:19 UTC, stepanpopov commented on hw/code/ui/pages/adv_page.py
> +)
убрал

2024-01-13 13:19 UTC, stepanpopov commented on hw/code/ui/pages/base_page.py
>          time.sleep(3)
поменял логику

2024-01-13 13:19 UTC, stepanpopov commented on hw/code/ui/pages/base_page.py
> +        return self.driver.get_cookie(AUTH_COOKIE_NAME) != None
дане

2024-01-13 13:19 UTC, stepanpopov commented on hw/code/ui/pages/base_page.py
>          # self.is_opened()
дон

2024-01-13 13:19 UTC, stepanpopov commented on hw/code/ui/pages/main_page/main_page.py
исправил конструктор пэйджи

2024-01-14 15:15 UTC, yarikTri requested changes

2024-01-14 15:15 UTC, yarikTri commented on hw/code/ui/fixtures.py
24 строка - можно заюзать url_cmp_pref из BasePage, либо перенести эту функу туда

2024-01-14 15:15 UTC, yarikTri commented on hw/code/tests/test_group_adv.py
>          group_adv_page.click_device_region().remove_device(0).remove_device(1)
Вынести осмысленные константы для 0 и 1

2024-01-14 15:17 UTC, yarikTri requested changes

2024-01-14 15:17 UTC, yarikTri commented on hw/code/ui/pages/company_page.py
> +    def is_matching_link(self, link, base_url):
Можно заюзать url_cmp_pref из BasePage, либо перенести эту функу туда

2024-01-14 18:54 UTC, merged